name: sapers
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter
  firebase_core: ^3.8.0
  cloud_firestore: ^5.5.0
  firebase_auth: ^5.3.3
  provider: ^6.1.2
  flutter_highlighting: ^0.9.0+11.8.0
  random_avatar: ^0.0.8
  intl: ^0.19.0
  file_picker: ^8.1.5
  firebase_storage: ^12.3.7
  url_launcher: ^6.3.1
  easy_sidemenu: ^0.6.0
  rxdart: ^0.28.0
  pasteboard: ^0.3.0
  crypto: ^3.0.6

 
 
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  generate: true 
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/tabmarker.png

