class Texts {
  static String defaultLanguageIfMissing = 'en';
  static Set<String> supportedLanguages = {'es', 'en'};

  static final Map<String, Map<String, String>> _texts = {
    'es': {
      'finding_users': 'Buscando usuarios...',
      'verMenos': 'Ver menos',
      'verMas': 'Ver más',
      'expertTab': 'Perfil de experto',
      'tarife': 'Tarifa/Hora',
      'view_on_map': 'Ver en mapa',
      'expertMode': 'Modo experto',
      'crearPost': 'Crear post',
      'descripcionTab': 'Descripción',
      'chatTab': 'Chat',
      'filesTab': 'Archivos',
      'addAttachment': 'Añadir adjunto',
      'buscar': 'Buscar...',
      'filtrarPorModulo': 'Filtrar por módulo',
      'mostrarMenu': 'Mostrar menú',
      'cerrarSesion': 'Cerrar sesión',
      'allmodules': 'Todos los módulos',
      'writeYourMessage': 'Escribe tu mensaje aquí...',
      'escribeTuRespuesta': 'Escribe tu respuesta aquí...',
      'formatearCodigoABAP': 'Formatear código ABAP',
      'copiarAlPortapapeles': 'Copiar al portapapeles',
      'responder': 'Responder',
      'serElPrimeroEnResponder': 'Sé el primero en responder',
      'titulo': 'Título',
      'now': 'Ahora',
      'descripcion': 'Descripción',
      'moduloSAP': 'Módulo SAP',
      'cancelar': 'Cancelar',
      'publicar': 'Publicar',
      'crearNuevoPost': 'Crear nuevo post',
      'noPostsDisponibles': 'No hay posts disponibles',
      'editarPerfil': 'Editar Perfil',
      'createPerfilRequiredFields': 'Todos los campos son requeridos',
      'guardar': 'Guardar',
      'nombreField': 'Username',
      'bioField': 'Bio',
      'noMemberOfProyect': 'No eres miembro de este proyecto',
      'locationField': 'Ubicación',
      'websiteField': 'Web/LinkedIn',
      'crearCuenta': 'Crear cuenta',
      'iniciarSesion': 'Iniciar sesión para ver más', 
      'postDestacados': 'Posts destacados',
      'emailField': 'Email',
      'emailValidate': 'Por favor ingresa tu email',
      'emailWrong': 'El email no es válido',
      'passField': 'Contraseña',
      'passError': 'Error',
      'passErrorLen': 'La contraseña debe tener al menos 6 caracteres',
      'confirmarContraseña': 'Confirmar Contraseña',
      'porFavorConfirmaTuContraseña': 'Por favor confirma tu contraseña',
      'lasContraseñasNoCoinciden': 'Las contraseñas no coinciden',
      'stars': 'Estrellas',
      'givestar': 'Reconocer',
      'attachments': 'Adjuntos',
      'conectar': 'xConecta',
      'seguir': 'Seguir',
      'unfollow': 'Dejar de seguir',
      'experiencia': 'Experiencia',
      'reviews': 'Reseñas',
      'feedGeneralTab': 'General',
      'FollowingTab': 'Siguiendo',
      'FollowersTab': 'Seguidores',
      'joinedOn': 'Se unió en',
      'noposts': 'No hay publicaciones disponibles',
      'mensajes': 'Mensajes',
      'projects': 'Invitaciones a proyectos',
      'send_project_invitation': 'Enviar invitación a proyecto',
      'messageSent': 'Mensaje enviado',
      'send': 'Enviar',
      'accept': 'Aceptar',
      'reject': 'Rechazar',
      'noprojects': 'No hay proyectos disponibles',
      'nuevoProyecto': 'Nuevo proyecto',
      'nombreDelProyecto': 'Nombre del proyecto',
      'tagsSeparadosPorComas': 'Tags',
      'crear': 'Crear',
      'projectsTab': 'Proyectos',
      'separarConEspacios': 'Separar con espacios',
      'escribeRespuesta': 'Escribe tu respuesta aquí...',
      'projectChat': 'Chat del proyecto',
      'projectDescr': 'Descripción del proyecto',
      'notMember': 'No eres miembro de este proyecto',
      'projectFiles': 'Archivos',
      'selectProject': 'Selecciona un proyecto',
      'close': 'Cerrar',
      'open': 'Crear',
      'genteTab': 'Gente',
      'mustBeLogged': 'Debes iniciar sesión para acceder a esta sección',
      'trendingTags': 'Tags populares',
      'activateExpertMode': 'Activa para ofrecer servicios de consultoría SAP',
      'expert': "Experto SAP",
      'pressLocation': 'Pulsa para obtener tu ubicación',
      'noMessages': 'Sin invitaciones aún',
      'sendInvitation': 'Enviar',
      'posts': 'Publicaciones',
      'fare': 'Tarifa',
      'usernameExists': 'El nombre de usuario ya existe',
      'askMe': 'Pregúntame algo sobre SAP',
      'recommendedPosts': 'Posts recomendados',
      'noMessagesChat': 'Sin mensajes',
      'TopContributors': 'Top Sapers',
      'feedTab': 'Feed',
      'personasTab': 'Personas',
      'customModule': 'Módulo personalizado',
      'Level': 'Nivel',
      'selectChat': 'Seleccionar chat',
      'messages': 'Mensajes',
      'typeMessage': 'Escribe un mensaje...',
      'messagesScreen': 'Mensajes',
      'sendMessage': 'Enviar mensaje',
      'matchingContent': 'Contenido coincidente',
      'iniciarSesionParaVerMas': 'Inicia sesión para ver más',
      'featuredUsers': 'Recomendados',
      'editProfile': 'Editar perfil',
      'bio': 'Bio',
      'location': 'Ubicación',
      'website': 'Web/LinkedIn',
      'specialty': 'Especialidad',
      'experience': 'Experiencia',
    },
    'en': {
      'bio': 'Bio',
      'noMemberOfProyect': 'You are not a member of this project',
      'postDestacados': 'Featured posts',
      'experience': 'Experience',
      'location': 'Location',
      'website': 'Website/LinkedIn',
      'specialty': 'Specialty',
      'finding_users': 'Finding users...',
      'matchingContent': 'Matching content',
      'sendMessage': 'Send message',
      'messagesScreen': 'Messages',
      'typeMessage': 'Type a message...',
      'selectChat': 'Select chat',
      'messages': 'Messages',
      'verMenos': 'See less',
      'feedTab': 'Feed',
      'personasTab': 'People',
      'verMas': 'See more',
      'allmodules': 'All modules',
      'recommendedPosts': 'Recommended posts',
      'expertTab': 'Expert profile',
      'askMe': 'Ask me anything about SAP',
      'usernameExists': 'Username already exists',
      'view_on_map': 'View on map',
      'joinedOn': 'Joined in',
      'fare': 'Fare',
      'posts': 'Posts',
      'tarife': 'Tarife/Hour',
      'FollowersTab': 'Followers',
      'sendInvitation': 'Send',
      'noMessages': 'No invitations yet.',
      'pressLocation': 'Press to get your location',
      'expert': 'SAP Expert',
      'expertMode': 'Expert mode',
      'activateExpertMode': 'Activate to offer SAP consulting services',
      'trendingTags': 'Trending tags',
      'mustBeLogged': 'You must be logged in to access this section',
      'genteTab': 'People',
      'close': 'Close',
      'open': 'Create',
      'crearPost': 'Create post',
      'descripcionTab': 'Description',
      'chatTab': 'Chat',
      'filesTab': 'Files',
      'addAttachment': 'Add attachment',
      'attachments': 'Attachments',
      'givestar': 'Recognize',
      'buscar': 'Search...',
      'now': 'Ahora',
      'filtrarPorModulo': 'Filter by module',
      'mostrarMenu': 'Show menu',
      'cerrarSesion': 'Log out',
      'writeYourMessage': 'Write your message here...',
      'escribeTuRespuesta': 'Write your answer here...',
      'formatearCodigoABAP': 'Format ABAP code',
      'copiarAlPortapapeles': 'Copy to clipboard',
      'responder': 'Reply',
      'serElPrimeroEnResponder': 'Be the first to reply',
      'titulo': 'Title',
      'descripcion': 'Description',
      'moduloSAP': 'SAP Module',
      'cancelar': 'Cancel',
      'publicar': 'Publish',
      'crearNuevoPost': 'Create new post',
      'noPostsDisponibles': 'No results found',
      'editarPerfil': 'Editar Perfil',
      'createPerfilRequiredFields': 'All fields are required',
      'guardar': 'Save',
      'nombreField': 'Username',
      'bioField': 'Bio',
      'locationField': 'Location',
      'websiteField': 'Website/LinkedIn',
      'crearCuenta': 'Create account',
      'iniciarSesion': 'Sign in',
      'iniciarSesionParaVerMas': 'Sign in to see more',
      'emailField': 'Email',
      'emailValidate': 'Please enter your email',
      'emailWrong': 'Email is not correct',
      'passField': 'Password',
      'passError': 'Error',
      'passErrorLen': 'Password must contain at least 6 characters',
      'confirmarContraseña': 'Confirm Password',
      'porFavorConfirmaTuContraseña': 'Please confirm your password',
      'lasContraseñasNoCoinciden': 'Passwords do not match',
      'conectar': 'xConnect',
      'seguir': 'Follow',
      'unfollow': 'Unfollow',
      'experiencia': 'Experience',
      'reviews': 'Reviews',
      'feedGeneralTab': 'General',
      'FollowingTab': 'Following',
      'noposts': 'No posts available',
      'mensajes': 'Messages',
      'projects': 'Project invitations',
      'send_project_invitation': 'Send project invitation',
      'messageSent': 'Message sent',
      'send': 'Send',
      'accept': 'Accept',
      'reject': 'Reject',
      'noprojects': 'No projects available',
      'nuevoProyecto': 'New project',
      'nombreDelProyecto': 'Project name',
      'tagsSeparadosPorComas': 'Tags',
      'crear': 'Create',
      'projectsTab': 'Projects',
      'separarConEspacios': 'Separate with spaces',
      'escribeRespuesta': 'Write your answer here...',
      'projectChat': 'Project chat',
      'projectDescr': 'Project description',
      'notMember': 'You are not a member of this project',
      'projectFiles': 'Files',
      'selectProject': 'Select a project',
      'noMessagesChat': 'No messages',
      'TopContributors': 'Top Sapers',
      'customModule': 'Custom Module',
      'Level': 'Level',
      'featuredUsers': 'Recommended',
      'editProfile': 'Edit Profile',
    },
  };

  static String translate(String key, String language) {
    return _texts[language]?[key] ?? key;
  }
}

class Modules {
  static final List<String> modules = [
    'FI',
    'CO',
    'MM',
    'SD',
    'PP',
    'PM',
    'HR',
    'ABAP',
    'BASIS'
  ];
}
